echo 'apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: horlandohorla1992/spring1:app-94f4617595
          ports:
            - containerPort: 80 
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
  namespace: default
spec:
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort' > deployment.yaml
